#!/bin/bash

SOURCE_PATH='/workspaces/gemini-cli'
TARGET_PATH='/workspaces/main'

cd $SOURCE_PATH

if [ ! -d "$TARGET_PATH" ]; then
    git worktree add -f $TARGET_PATH origin/main
fi

# Copy the GEMINI.md file from the main branch to the current directory
cd $TARGET_PATH/docs/

# Configure Context for Gemini CLI
if [ -f "$TARGET_PATH/GEMINI.md" ]; then
  rm -f $TARGET_PATH/GEMINI.md
  git update-index --assume-unchanged $TARGET_PATH/GEMINI.md
fi

cp $SOURCE_PATH/docs/GEMINI.md $TARGET_PATH/docs/GEMINI.md

mkdir -p $TARGET_PATH/docs/.gemini
touch $TARGET_PATH/docs/.gemini/system.md
touch $TARGET_PATH/docs/.gemini/settings.json

# Use a temp folder for .gemini
# GEMINI_TEMP_DIR=$(mktemp -d)
# mkdir -p "$GEMINI_TEMP_DIR"

cat <<'EOF' | tee $TARGET_PATH/docs/.gemini/settings.json > /dev/null
{
  "coreTools": ["run_shell_command", "read_file", "write_file", "replace"]
}
EOF

cat <<'EOF' | tee $TARGET_PATH/docs/.gemini/system.md > /dev/null
You are a certified professional translator (EN➜ZH-TW) specialized in IT and software localization.
Guidelines:
1. Translate the user's input from English to Traditional Chinese. If the user's input file already translated, just ignore it.
2. Keep the original paragraph breaks; preserve Markdown syntax.
3. Use terminology from the following glossary:
   - "codebase" = "程式碼基底"
   - "build" = "建置"
   - "comprehensive guide" = "完整指南"
   - "Welcome to Gemini CLI documentation" = "歡迎使用 Gemini CLI 使用手冊"
4. Maintain formal yet reader-friendly tone suitable for end-user documentation.
5. Do NOT answer questions or add explanations; output only the translated text.
6. If a term is ambiguous, append "[不確定]" after the term.
7. If the user provides HTML, keep tags intact.
8. Revise the translation to ensure accuracy.
9. Do not translate any error messages or system prompts.
10. 翻譯完成後，請將需要固定翻譯詞彙的對對照更新 GEMINI.md 檔案。
EOF

cp $TARGET_PATH/CONTRIBUTING.md $TARGET_PATH/docs/CONTRIBUTING.md

cat <<'EOF' | tee $TARGET_PATH/docs/temp_translate.sh > /dev/null
#!/bin/bash

files=(
  "./file1.md"
  "./folder1/file2.md"
)

for filename in "${files[@]}"; do
  mkdir -p logs/$(dirname "$filename")
  echo "gemini-translator -m gemini-2.5-pro --debug -i $filename -o $filename 2>&1 > logs/$filename.log &"
  gemini-translator -m gemini-2.5-pro --debug -i $filename -o $filename 2>&1 > logs/$filename.log  &
done

echo "Waiting for translations to complete..."
wait
EOF

  # echo "Translate @$filename to zh-tw and edit the same file accordingly."
  # gemini -y -p "Translate input file to zh-tw and edit the same file accordingly. Input file: @$filename" > logs/$filename.log &
  

cat <<'EOF' | gemini -y -p
Please follow these steps to translate the Gemini CLI documentation. Step by step instructions are provided below.

1. Use the following shell command to find all Markdown documents to be translated:

    ```sh
    find . -type f -name '*.md' ! -name 'GEMINI.md' ! -path './.gemini/system.md'
    ```

2. Use the following shell command to identify all modified files, as these files are considered already translated:

    ```sh
    git status --porcelain | awk '/^.. docs\// {sub("^.. docs/", ""); print}' | grep -v GEMINI.md | grep -v .sh | grep -v logs/
    ```

3. List all files that need to be translated.

4. Edit `temp_translate.sh` script that modify `files` variable to lists all files requiring translation. Only edit the `files` variable. Avoid altering any other part of the code. Make sure to replace the file paths with the actual paths of the files that need translation.
EOF

echo "Current Path: `pwd`"
cd $TARGET_PATH/docs/

# 5. Show the full path and the content of the shell script `temp_translate.sh`.
echo "The shell script to translate the files is located at: $TARGET_PATH/docs/temp_translate.sh"
echo "Content of the shell script:"
echo '------------------------------'
cat $TARGET_PATH/docs/temp_translate.sh
echo '------------------------------'
echo

# 6. Run the shell script been generated by the above command to translate all files that need to be translated.
echo "Running the translation script..."
bash $TARGET_PATH/docs/temp_translate.sh
echo "done."

echo "Fixing links in index.md..."
sed -i 's|\.\./CONTRIBUTING\.md|\.\/CONTRIBUTING\.md|g' index.md

echo "Fixing page titles..."
find . -type f -name '*.md' -exec sed -i '1s/^# Gemini CLI：/# /' {} \;
find . -type f -name '*.md' -exec sed -i '1s/^# Gemini CLI 的/# /' {} \;
find . -type f -name '*.md' -exec sed -i '1s/^# Gemini CLI /# /' {} \;

echo "Copying translated files to the source path..."
find . -type f -name '*.md' ! -path './.gemini/system.md' -exec cp {} $SOURCE_PATH/docs/{} \;

echo "Translation completed. Please check the logs for details."
