name: Codex Runner

on:
  issue_comment:
    types:
      - created

jobs:
  codex:
    if: startsWith(github.event.comment.body, '/codex')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    env:
      AZURE_BASE_URL: ${{ vars.AZURE_BASE_URL }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      CODEX_UNSAFE_ALLOW_NO_SANDBOX: ${{ vars.CODEX_UNSAFE_ALLOW_NO_SANDBOX }}
      CODEX_SANDBOX_NETWORK_DISABLED: ${{ vars.CODEX_SANDBOX_NETWORK_DISABLED }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install Codex CLI
        run: npm install -g @willh/codex
      - id: run-codex
        name: Run Codex
        run: |
          BODY="${{ github.event.comment.body }}"
          PROMPT="${BODY#'/codex '}"

          # 使用 tee 將輸出同時顯示在終端和保存到暫存檔
          TEMP_FILE=$(mktemp)
          echo "Created temporary file: $TEMP_FILE"

          # 設定環境變數禁用 raw mode 以支援 CI 環境
          export CI=true
          export FORCE_COLOR=0
          export NODE_ENV=production
          export TERM=dumb

          # Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
          # 這個問題目前無解: 
          codex --full-auto -q "$PROMPT" < /dev/null | tee "$TEMP_FILE"

          # 從暫存檔中取得最後一行 JSON
          LAST_JSON="$(tail -n 1 "$TEMP_FILE")"

          # 檢查 status 是否為 completed
          STATUS="$(echo "$LAST_JSON" | jq -r '.status // empty')"

          if [ "$STATUS" = "completed" ]; then
            # 提取 content[0].text 的內容
            CONTENT="$(echo "$LAST_JSON" | jq -r '.content[0].text // empty')"
            echo "result<<EOF" >> $GITHUB_OUTPUT
            printf "%s\n" "$CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            # 如果狀態不是 completed，輸出錯誤訊息
            echo "result<<EOF" >> $GITHUB_OUTPUT
            echo "Error: Codex execution did not complete successfully. Status: $STATUS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

          # 清理暫存檔
          rm -f "$TEMP_FILE"
          echo "Cleaned up temporary file: $TEMP_FILE"
      - name: Comment Codex response
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            **Codex response:**
            ```
            ${{ steps.run-codex.outputs.result }}
            ```